services:
  php:
    image: ramageek/image:php8.3-laravel
    volumes:
      - '.:/var/www/html'
    networks:
      - proxy
  redis:
    image: redis:alpine
    networks:
      - proxy
networks:
  proxy:
    driver: bridge
    external: true
